### ISSUE TITLE
Instructions, please :)

### ISSUE THREAD

**Issue by ovsw** [dschewchenko/nuxt-svgicon#1]
Hi! Can you please add instructions on how to use? Tried to figured it out on my own but I'm a nuxt novice and couldn't do it.. Will help with testing!

Thanks for your work!

**Comment by dschewchenko** [comment]
Hello. I have no time for this now. But it's in progress. Will be in near future)

**Comment by dschewchenko** [comment]
Require module as described in nuxt docs.
Put your svgs in directory 'assets/svg/'
And after building use it in components, as described in svg-icon readme. 
<svgicon name="name_of_your_svg">

All svgs will be rendered in html. Each subdirectory will be namespace for icons.
