### ISSUE TITLE
Error on when run dev

### ISSUE THREAD

**Issue by tranghaviet** [dschewchenko/nuxt-svgicon#3]
When I run dev server the `index.js` was import wrong files so I get error file not found.

My nuxt config:

```js
[
  'nuxt-svgicon', {
      tagName: 'svg-icon',
      sourcePath: 'svg-icons',
      targetPath: 'components/compiled-icons',
    }
]
```

I put all svg icons in **svg-icons** folder

The generated files in **components/compiled-icons** folder:

![image](https://user-images.githubusercontent.com/23404016/50050631-60c51780-0133-11e9-9d8d-c8b09ea122ad.png)

The `components/compiled-icons/index.js` file:

```js
/* eslint-disable */
import './chevron-up-circle.js'
import './new-solid.js'
import './plus-circle.js'
```

Please help me :(

**Comment by dschewchenko** [comment]
Hi. 
Set subDir option the same as sourcePath. And all will be good :)

**Comment by dschewchenko** [comment]
In next release I will set subDir same as sourcePath by default

**Comment by tranghaviet** [comment]
Hope to see it. Good work @dschewchenko :D
