### ISSUE TITLE
Recursive loops create countless files on windows10

### ISSUE THREAD

**Issue by Nirodhiko** [dschewchenko/nuxt-svgicon#6]
e.g   svg\bundle\assets\svg\assets\svg\assets\svg\assets\svg\assets\svg...... Infinite loop.

**Comment by kskrlinnorth2** [comment]
@shun89 How did you fix this? I also step into infinite loop with default settings

**Comment by rublev** [comment]
> @shun89 How did you fix this? I also step into infinite loop with default settings

Clone the library and make your own changes lmao, this library is a nightmare.

**Comment by kskrlinnorth2** [comment]
I stopped using it the same day lol
